### ISSUE TITLE
마일리지 수혜자 분석 관련 차트 API 구현

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#100]
**Description**
마일리지 수혜자 분석 관련 차트 API 구현

**Todo**
- [x] 학생의 마일리지 가중치 분포 조회 API 구현
- [x] 카테고리 별로 몇개의 마일리지 활동이 있는지 조회 API 구현
- [x] 학년별로 마일리지 수혜 학생 분포 조회 API 구현 
- [x] 학부 별로 마일리지 수혜 학생 분포 조회 API 구현

**ETC**
