### ISSUE TITLE
Category, Activity CRUD API 구현 

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#2]
**Description**
- Category, Activity Entity의 CRUD를 구현

**Todo**
- [x] Category Create API
- [x] Category Read API
- [x] Category Read ALL API
- [x] Category Update API
- [x] Category Delete API
- [x] Activity Create API
- [x] Activity Read API
- [x] Activity Read ALL API
- [x] Activity Update API
- [x] Activity Delete API

**ETC**
Activity의 data필드를 어떻게 하면 효율적으로 관리할 수 있을지가 제일 고민
