### ISSUE TITLE
Manager CRUD, 회원가입, 승인 API 구현

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#24]
**Description**
- Manager 관련 API 구현

**Todo**
- [x] Manager ERD 수정
- [x] Manager Create API 구현
- [x] Manager Read API 구현
- [x] Manager Update API 구현
- [x] Manager Delete API 구현
- [x] 회원가입 API 구현
- [x] Manager 가입 승인 API 구현

**ETC**
