### ISSUE TITLE
Activity, Participant Entity 수정  

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#28]
**Description**
- Activity Entity 수정

**Todo**
- [x] startDate, endDate 삭제
- [x] Participant에 section 추가 : Enum으로 사용
- [x] Entity 변경에 따른 모든 API 수정

**ETC**
