### ISSUE TITLE
API 인가 기능 관련 수정 

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#36]
**Description**
- API 인가 기능 관련 수정 

**Todo**
- [x] Super Manager, 일반 Manager 구분
- [x] Manager 만 사용 가능하도록
- [x] Login 한 유저 즉 학생 Manager 둘 다 사용 가능하도록 

**ETC**
