### ISSUE TITLE
마일리지 활동 신청 API, 활동 신청 승인 API 구현

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#63]
**Description**
마일리지 활동 신청 API, 활동 신청 승인 API 구현

**Todo**
- [x] API 구현하기 위한 ERD 확인 및 수정
- [x] 마일리지 활동 신청 API 
- [x] 활동 신청 승인 API 구현

**ETC**
