### ISSUE TITLE
Activity, Mileage 차트 관련 API 구현

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#65]
**Description**
마일리지 활동 신청 API, 활동 신청 승인 API 구현

**Todo**
- [x] 자신이 참여했던 학기들 불러오는 API 구현
- [ ] 카테고리 마다 학생이 참여한 마일리지활동 수, 평균수 보내주는 API 구현
- [ ] 자신의 학기마다 마일리지 활동 갯수 구해주는 API 구현
- [ ] 자신의 학기마다, 학년에 따른 자신의 위치의 랭크 API 구현
- [ ] 모든학기 또는 학기마다 평균으로 섹션마다 자신이 참여한 활동 수 보내주는 API 구현

**ETC**
