### ISSUE TITLE
Department, Major, Category의 기존 API의 추가적인 기능 구현

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#92]
**Description**
Department, Major, Category의 기존 API 기능 추가 

**Todo**
- [ ] Department에 지도 교수 성함, 학부 전화번호, 총 인원까지 보여주기
- [ ] Department Create, Read, Update API 수정
- [ ] 전공의 Read API에 전공별로 학년별로 몇명씩 있는지 
- [ ] 카테고리 Read에 마일리지 활동 갯수 추가
- [ ] 카테고리 Domain에 memo라는 추가적인 정보 입력

**ETC**
