### ISSUE TITLE
마일리지 활동 분석 차트 API 구현 

### ISSUE THREAD

**Issue by gomster96** [HisPath/HisPath-Server#97]
**Description**
마일리지 활동 분석 차트 API 구현

**Todo**
- [x] 마일리지 활동 카테고리 관련 차트 API 구현
- [x] Rank 차트 관련 API 구현
- [x] Timeline 차트 관련 API 구현 

**ETC**
